# Generated by Django 5.0.3 on 2024-03-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
