name: Create Terraform Backend Resources
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Environment to create the terraform backend resources"   
        options:
          - dev
          - staging
          - prod
jobs:
  provision-s3-and-dynamodb:
    runs-on: ubuntu-latest
    env:
      environment: ${{github.event.inputs.environment}}
      region: us-east-1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.region}}

      - name: Create S3 Bucket
        run: |
          aws s3api create-bucket \
            --bucket trakdip-terraform-state-${{env.environment}} \
            --region ${{env.region}}
          
      - name: Enable Versioning for S3 Bucket
        run: |
          aws s3api put-bucket-versioning \
            --bucket trakdip-terraform-state-${{env.environment}} \
            --versioning-configuration Status=Enabled

      - name: Check if DynamoDB Table Exists
        id: check-dynamodb-table
        run: |
          set -e
          if aws dynamodb describe-table --table-name trakdip_terraform_locks; then
            echo "TableExists=true"
          else
            echo "TableExists=false"
          fi

      - name: Create DynamoDB Table for Terraform State Locking
        if: steps.check-dynamodb-table.outputs.TableExists == 'false'
        run: |
          aws dynamodb create-table \
            --table-name trakdip_terraform_locks \
            --attribute-definitions AttributeName=LockID,AttributeType=S \
            --key-schema AttributeName=LockID,KeyType=HASH \
            --billing-mode PAY_PER_REQUEST
